// Generated by build.mjs. Edit products.json instead.
window.PS_PRODUCTS = [
 {
  "slug": "rave-classic",
  "name": "Rave Classic",
  "url": "https://pep-schep.nl/shop/rave-classic/",
  "wcId": null,
  "price": null,
  "blurb": "Minimalistisch maar uitgesproken. Scherpe rechte lijnen in een dun zwart montuur.",
  "lens": "Donker glas",
  "tint": "#2B2B30",
  "tintAlpha": 0.62,
  "frameColor": "#141414",
  "frameOpacity": 1,
  "lenses": [
   "M58 72 H276 V160 Q276 176 260 176 H74 Q58 176 58 160 Z",
   "M324 72 H542 V160 Q542 176 526 176 H340 Q324 176 324 160 Z"
  ],
  "extra": "M276 92 Q300 80 324 92 M58 78 L14 70 M542 78 L586 70"
 },
 {
  "slug": "el-silencio",
  "name": "El Silencio",
  "url": "https://pep-schep.nl/shop/el-silencio/",
  "wcId": null,
  "price": 19.95,
  "blurb": null,
  "lens": null,
  "tint": "#3A3531",
  "tintAlpha": 0.55,
  "frameColor": "#2A2521",
  "frameOpacity": 1,
  "lenses": [
   "M62 78 Q62 64 80 64 H262 Q280 64 278 84 L270 140 Q262 184 196 186 H128 Q70 184 64 136 Z",
   "M538 78 Q538 64 520 64 H338 Q320 64 322 84 L330 140 Q338 184 404 186 H472 Q530 184 536 136 Z"
  ],
  "extra": "M278 88 Q300 72 322 88 M62 76 L16 66 M538 76 L584 66"
 },
 {
  "slug": "sinix",
  "name": "Sinix",
  "url": "https://pep-schep.nl/shop/sinix/",
  "wcId": null,
  "price": 19.95,
  "blurb": "Y2K-racer met smalle, naar achter getrokken lijnen en een diep donker glas.",
  "lens": "Diep donker glas",
  "tint": "#16181D",
  "tintAlpha": 0.72,
  "frameColor": "#1A1B1F",
  "frameOpacity": 1,
  "lenses": [
   "M30 104 Q46 70 120 66 L282 70 Q300 76 300 96 Q300 76 318 70 L480 66 Q554 70 570 104 Q560 146 470 152 L340 150 Q306 148 300 124 Q294 148 260 150 L130 152 Q40 146 30 104 Z"
  ],
  "extra": "M30 104 Q10 98 4 90 M570 104 Q590 98 596 90"
 },
 {
  "slug": "cristal-gris",
  "name": "Cristal Gris",
  "url": "https://pep-schep.nl/shop/cristal-gris/",
  "wcId": null,
  "price": null,
  "blurb": null,
  "lens": null,
  "tint": "#7F868D",
  "tintAlpha": 0.5,
  "frameColor": "#B9BDC1",
  "frameOpacity": 0.55,
  "lenses": [
   "M62 78 Q62 64 80 64 H262 Q280 64 278 84 L270 140 Q262 184 196 186 H128 Q70 184 64 136 Z",
   "M538 78 Q538 64 520 64 H338 Q320 64 322 84 L330 140 Q338 184 404 186 H472 Q530 184 536 136 Z"
  ],
  "extra": "M278 88 Q300 72 322 88 M62 76 L16 66 M538 76 L584 66"
 },
 {
  "slug": "calora",
  "name": "Calora",
  "url": "https://pep-schep.nl/shop/calora/",
  "wcId": null,
  "price": null,
  "blurb": "Transparant montuur, lichtblauwe glazen. Fris, en past bij alles.",
  "lens": "Lichtblauw glas",
  "tint": "#8FC3E4",
  "tintAlpha": 0.42,
  "frameColor": "#E9EEF0",
  "frameOpacity": 0.55,
  "lenses": [
   "M92 60 H244 Q258 60 268 68 L278 78 Q286 86 286 100 V156 Q286 188 254 188 H96 Q64 188 64 156 V100 Q64 86 72 78 L82 68 Q86 60 92 60 Z",
   "M508 60 H356 Q342 60 332 68 L322 78 Q314 86 314 100 V156 Q314 188 346 188 H504 Q536 188 536 156 V100 Q536 86 528 78 L518 68 Q514 60 508 60 Z"
  ],
  "extra": "M286 92 Q300 82 314 92 M64 86 L22 80 M536 86 L578 80"
 },
 {
  "slug": "lunares",
  "name": "Lunares",
  "url": "https://pep-schep.nl/shop/lunares/",
  "wcId": null,
  "price": null,
  "blurb": null,
  "lens": null,
  "tint": "#5A4636",
  "tintAlpha": 0.5,
  "frameColor": "#2C2420",
  "frameOpacity": 1,
  "lenses": [
   "M172 38 A84 84 0 1 1 171.9 38 Z",
   "M428 38 A84 84 0 1 1 427.9 38 Z"
  ],
  "extra": "M252 108 Q300 84 348 108 M90 112 L20 96 M510 112 L580 96"
 },
 {
  "slug": "tecna",
  "name": "Tecna",
  "url": "https://pep-schep.nl/shop/tecna/",
  "wcId": null,
  "price": null,
  "blurb": null,
  "lens": null,
  "tint": "#44484E",
  "tintAlpha": 0.55,
  "frameColor": "#1F2124",
  "frameOpacity": 1,
  "lenses": [
   "M40 86 Q60 52 300 50 Q540 52 560 86 L548 138 Q530 176 420 178 Q340 176 312 150 Q300 140 288 150 Q260 176 180 178 Q70 176 52 138 Z"
  ],
  "extra": "M40 86 L6 76 M560 86 L594 76"
 }
];
